### ISSUE TITLE
HiC --> pacbio CLR

### ISSUE THREAD

**Issue by Johnsonzcode** [HudsonAlpha/rust-fmlrc#19]
Hello, @holtjma 
Thanks for your great work. Can I use Hi-C reads to correct pacbio CLR reads ? 
I am wondering whether Hi-C reads are complete fragment(eg. 150bp from one chromosome ) or them are incomplete that Hi-C reads are composed of different fragment(eg. Hi-C reads are150bp which is composed of 60 bp from one chromosome and 90 bp from another chromosome or 90 from same chromosome but other location).

**Comment by holtjma** [comment]
I'm probably not the best person to answer this.  I haven't worked with Hi-C data before so I'm unfamiliar with the pitfalls and whether this would theoretically work or not.  @txje do you have any thoughts on this?

**Comment by txje** [comment]
While we haven't used FMLRC with Hi-C data before, my expectation is that it will work without modification. There will be cases, as you describe, where reads chimeras are formed (by design) between distant parts of the genome within Hi-C reads, and the k-mers at these junctions will be included in the FM-index, but they should be in the minority, so they shouldn't affect the correction. The chimeric junctions will be treated kind of like regular Illumina sequencing errors.

**Comment by holtjma** [comment]
There's nothing in `fmlrc2` that is explicitly recognizing the chimeric junctions.  I think what @txje is saying is that those junctions should occur inconsistently so the corresponding k-mers will be low-frequency in the data.  This will cause `fmlrc2` to ignore those k-mers because they are low frequency, as if they were sequencing errors.  It won't explicitly discard any of the reads, but it may ignore portions of the reads corresponding to the junction assuming they are not frequent in the data.

**Comment by Johnsonzcode** [comment]
OK, I got it. Thanks for your explanation !
