### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by pezhmansafdari** [HudsonAlpha/rust-fmlrc#3]
Hi,

I receive this error when I am trying to compile:
error: linking with `cc` failed: exit code: 1

bunch of error lines and then:
= note: /local_scratch/psafdari/cargo-installWwSoz4/release/deps/libbzip2_sys-0266f88c67b1cd1c.rlib(decompress.o): In function `BZ2_decompress':
          decompress.c:(.text.BZ2_decompress+0x1534): undefined reference to `_intel_fast_memcpy'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: failed to compile `fmlrc v0.1.2`, intermediate artifacts can be found at `/local_scratch/psafdari/cargo-installWwSoz4`

Caused by:
  could not compile `fmlrc`

To learn more, run the command again with --verbose.

Cheers,
Pezhman

**Comment by holtjma** [comment]
Hi,

It's hard to tell exactly what went wrong from your error message, but it's likely that the system you're using for compilation is missing a set of intrinsics (specifically `_intel_fast_memcp`) required to install a _dependency_ of FMLRC (see your line with ` /local_scratch/psafdari/cargo-installWwSoz4/release/deps/libbzip2_sys-0266f88c67b1cd1c.rlib`).  Since the message is related to bz2, my gut says that this is because FMLRC is dependent on flate2 (it may not be flate2 that is failing, but a dependency it has).  

Since the error seems to be intrinsic related, it is _probably_ an issue with either your compiler setup or the actual hardware you're compiling on.  There's a decent chance you will need root access or (if in a cluster environment) you IT/sys-admin folks to help resolve the issue.

If you provided the full error, I could probably help trace that, but it's _unlikely_ that there's anything I can do to actually resolve the error for you.
