### ISSUE TITLE
Feature request- Number of changes made as part of output

### ISSUE THREAD

**Issue by zacksaud** [HudsonAlpha/rust-fmlrc#33]
Hi,

Given that the K-mer parameter can be altered and people have reported different results with running FLMRC2 more than once on a set of reads, is it possible to give the changes made during a run as output? Pilon have a flag that allows outputs to be listed (I appreciate that that is for use with contigs and not reads), but I think if a number is given it would be useful to know whether for a given set of reads more correction rounds with different K-mers improves/does anything.
It would also be great to quantify what altering the K-mer values does to the correction process.

Many thanks for a great tool! 

Best

Zack

**Comment by holtjma** [comment]
I'm not sure I understand what you're requesting.  If you want to see the differences before and after, wouldn't you just compare the uncorrected and then corrected reads against each other?  Presumably, the different reported results from altering K were done by running one or more times and then comparing the output.  

Can you clarify what you're requesting and maybe provide a toy example of what output you're wanting to see?

Matt

**Comment by zacksaud** [comment]
Hi Matt,

Thanks for the quick reply.

Firstly, I'll warn you that I am a complete novice at Bioinformatics and I will apologize in advance if I'm not very technical with my descriptions/clarifications.

Pilon has a flag that is explained with the following: 
--changes
"If specified, a file listing changes in the <output>.fasta will be generated."

Example of output:
NODE_edge_12+_length_4111539_cov_217:616071 NODE_edge_12+_length_4111539_cov_217_pilon:616071 . A
NODE_edge_12+_length_4111539_cov_217:631821 NODE_edge_12+_length_4111539_cov_217_pilon:631822 . T
NODE_edge_12+_length_4111539_cov_217:866230 NODE_edge_12+_length_4111539_cov_217_pilon:866232 T .
NODE_edge_12+_length_4111539_cov_217:1009618 NODE_edge_12+_length_4111539_cov_217_pilon:1009619 T .
NODE_edge_12+_length_4111539_cov_217:2639140 NODE_edge_12+_length_4111539_cov_217_pilon:2639140 C .
NODE_edge_12+_length_4111539_cov_217:2917037 NODE_edge_12+_length_4111539_cov_217_pilon:2917036 . T
NODE_edge_12+_length_4111539_cov_217:3249813 NODE_edge_12+_length_4111539_cov_217_pilon:3249813 . T
NODE_edge_12+_length_4111539_cov_217:3265329 NODE_edge_12+_length_4111539_cov_217_pilon:3265330 . A

I find it very useful when polishing ONT/hybrid assembled genomes with Illumina reads (mainly to know when to stop polishing) and it would be great if FMLRC2 could list the changes it makes to assembled scaffolds as output (I've read a few blogs/tweets where people have said using FMLRC2 for polishing post assembly fixes errors all other tools miss, I've certainly found FMLRC2 to improve Fungal genome assemblies as determined by BUSCO scores).

I'm guessing the kind of output listed above wouldn't be possible when correcting long reads prior to assembly (given that there may be millions of changes), but I think it would be very useful to know how many bases overall were: 
1. substituted 
2. deleted 
3. added
I do not possess the computational skills to extract this information when comparing FMLRC2's FASTA output to the FASTQ input (and I'm sure many others don't either). In this paper they state that multiple rounds of polishing with FMLRC2 prior to assembly yields better results (https://genomebiology.biomedcentral.com/articles/10.1186/s13059-023-03112-7), coupled with the fact that there are a few tweak-able parameters (e.g. -k, min_frac) that may alter the corrections process, it would be good to have the changes made as output so the user can observe what changes are made and tweak things to fine the 'sweet spot' for their specific purpose.

Best

Zack

**Comment by holtjma** [comment]
In the short term, this feature is unlikely to happen. I can see a couple ways this might be done, but they each have some issues:

1. We could output the changes that FMLRC makes individually. Whenever a correction is made, just output the sequence ID, position, original sequence, and the new sequence.  However, this becomes complicated to interpret when there are multiple k-mer passes that may create overlapping corrections and also shifts in the sequence. Doing this in a useful way is likely a large feature, one that I currently do not have time allocated for.  I'm also not convinced that it's better than just...
2. Comparing the sequences before and after via mapping. This will skip the intermediate steps and just provide the final comparison between the original sequence and the final sequence, similar to how a CIGAR string in a BAM file would. However, this can be done after FMLRC using the output files, and is really more of an evaluation step than a correction step. I suspect the researchers who have performed in-depth read correction or assembly polishing analyses have scripts/tools for this already that would be as good or better than anything I could incorporate.

Sorry this isn't a very satisfactory response, but I think your best bet is to reach out to those who have performed base-level polishing analyses and seeing if they have some pre-baked tools you could use. Otherwise, you could learn how to do the analyses yourself; tools like minimap2 would likely be useful in performing the alignments for you, then you only need to extract the differences.

**Comment by zacksaud** [comment]
Hi Matt,

Thanks for the informative reply. I completely understand, it was a request made in the hopes that it would be a simple thing to implement (with me having no idea of the technical requirements involved due to my lack of experience writing code for tools). I'll read up on the use of Minimap2 and see if I can come up with a simple metric to evaluate mapping scores/efficiencies.

Many thanks once again for the info

Best

Zack
